version: '3.7'

services:
  web:
    image: docker-swarm-node-app:latest
    deploy:
      replicas: 10
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - webnet
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    deploy:
      replicas: 1
    networks:
      - webnet

networks:
  webnet:
